### ISSUE TITLE
Elastic Search for SAC / SPA N2K forms and Ramsar RIS forms

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/jncc-website#45]
N2K and RIS forms will not be managed via TopCat/ResourceHub or through Umbraco so have no means of entering into the ES index.  We need a process that can be run periodically  (c.2 times per year for each) to generate / update the ES index for these PDFs.
These PDFs will live on the JNCC Umbraco web server in a virtual directory (already created) that is immune to code deployments.  Within that virtual directory, there will be subfolders called:

Virtua Directory (JNCC-assets?  need to confirm)
    /SAC-N2K
    /SPA-N2K
    /RIS

notes
could run from jenkins job?
Needs to be added as a task to the 'things to do for a tranche wiki page'

Files to use are here Z:\Prog110-FutureData\0077 Website development\temp-PDFs for search
Each batch of files (SPA, SAC, Ramsar) will need possibly different metadata added into the index.

**Comment by LynnHeeley** [comment]
keywords and clarity on requirements

**Comment by jonparsonsjncc** [comment]
Hi @felixMasonJncc 
When this task is complete could you move it to QA and add instructions for me to test

once passed then we need to ensure the files are moved to the live server and the index on the live site is updated

**Comment by jonparsonsjncc** [comment]
Hi @felixMasonJncc 
When this task is complete could you move it to QA and add instructions for me to test

once passed then we need to ensure the files are moved to the live server and the index on the live site is updated

**Comment by jonparsonsjncc** [comment]
need to also centralise all search code into one place as part of this project

**Comment by felixMasonJncc** [comment]
The two remaining issues that were causing messages from the asset indexer to error out in the sqs queue should have been fixed.

jncc-assets-indexer:
- Publication date is now iso format.
- Asset validator checks for uk format dates

elasticsearch-lambda-ingester
- Moved into the jncc-website-search project
- Updated document validator to include website-assets site. (Perhaps this list should be moved out to an env variable for easy reconfiguration?)

- Todo:
- Need to deploy a new version of the elasticsearch lambda to the aws.
- Need to remove the old repo. - Note the new repo contains code only, not commit history.

elasticsearch-delete-by-site (jenkins job)
- Moved the code for this into the jncc-website-search repo ]
- The existing jenkins job needs to be modified to use this code.

Note.
There's no jenkins file in the git solution, a pipeline is unncessary since it's just checking out and running a script.

**Comment by jonparsonsjncc** [comment]
Check with felix on progress

**Comment by jonparsonsjncc** [comment]
ensure the files are live and available on the server
see attached spreadsheet
[https://app.zenhub.com/files/129929612/16ca7bce-694a-482b-af12-46ba8c27be58/download](https://app.zenhub.com/files/129929612/16ca7bce-694a-482b-af12-46ba8c27be58/download)

**Comment by felixMasonJncc** [comment]
# Progress
- All jenkins jobs created
jncc-assets-indexer-beta - Indexes the jncc-assets folder in the beta jncc website
jncc-assets-indexer-beta - Same for live

- elasticsearch-delete-by-site - jenkins job now pulls code from jncc-website-search repo.

# Outstanding bits
- Awaiting new complete set of documents
- Adding live documents to index
- Finish documenting and scripting dev environment. - do this as prep for demo

**Comment by jonparsonsjncc** [comment]
awaiting ramsar data sheet - with start to re generate

**Comment by felixMasonJncc** [comment]
For testing plan see jncc-website #66
