### ISSUE TITLE
HTTP errors show "object moved" text in addition to the error page

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/jncc-website#67]
e.g. http://jncc.gov.uk/%3Cscript%3E

**Comment by felixMasonJncc** [comment]
Ok I don't think this is an issue really.
It happens because the error page is called from a http connection. The site attempts to redirect to https but the call has resulted in an error. So rather then redirecting the framework issues this text with a link the https version of the error page.

The first thing that happens to a users connection is that they are redirected to https. If an error occurs after that point there is no issue, they will see the 500 error page delivered over the https connection. There's no redirection involved. It's unlikely that the site would 500 before this redirection has taken place expect if someone came in directly to an erroring page from a link. However since users would almost certainly be on https when they copy a link to share I think this is an unlikely problem to occur.
